/* tslint:disable */
/* eslint-disable */
/**
 * PriceList Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface ListPriceListsRequestFilter
 */
export interface ListPriceListsRequestFilter {
    /**
     * 
     * @type {string}
     * @memberof ListPriceListsRequestFilter
     */
    'code'?: string;
    /**
     * 
     * @type {string}
     * @memberof ListPriceListsRequestFilter
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ListPriceListsRequestFilter
     */
    'description'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ListPriceListsRequestFilter
     */
    'isActive'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ListPriceListsRequestFilter
     */
    'isDefault'?: boolean;
    /**
     * 
     * @type {PricelistCurrencyFilter}
     * @memberof ListPriceListsRequestFilter
     */
    'currencyFilter'?: PricelistCurrencyFilter;
    /**
     * 
     * @type {boolean}
     * @memberof ListPriceListsRequestFilter
     */
    'vatIncluded'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ListPriceListsRequestFilter
     */
    'deliveredDutyPaid'?: boolean;
    /**
     * 
     * @type {PricelistSegmentFilter}
     * @memberof ListPriceListsRequestFilter
     */
    'segmentsFilter'?: PricelistSegmentFilter;
    /**
     * 
     * @type {PricelistMarketFilter}
     * @memberof ListPriceListsRequestFilter
     */
    'marketsFilter'?: PricelistMarketFilter;
    /**
     * 
     * @type {PricelistChannelFilter}
     * @memberof ListPriceListsRequestFilter
     */
    'channelsFilter'?: PricelistChannelFilter;
    /**
     * 
     * @type {PricelistPriceListTypeFilter}
     * @memberof ListPriceListsRequestFilter
     */
    'typeFilter'?: PricelistPriceListTypeFilter;
    /**
     * 
     * @type {boolean}
     * @memberof ListPriceListsRequestFilter
     */
    'isSystem'?: boolean;
}
