/* tslint:disable */
/* eslint-disable */
/**
 * PriceList Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface PricelistListPriceListsRequest
 */
export interface PricelistListPriceListsRequest {
    /**
     * 
     * @type {string}
     * @memberof PricelistListPriceListsRequest
     */
    'tenantId'?: string;
    /**
     * 
     * @type {number}
     * @memberof PricelistListPriceListsRequest
     */
    'pageSize'?: number;
    /**
     * 
     * @type {string}
     * @memberof PricelistListPriceListsRequest
     */
    'pageToken'?: string;
    /**
     * 
     * @type {string}
     * @memberof PricelistListPriceListsRequest
     */
    'searchQuery'?: string;
    /**
     * 
     * @type {string}
     * @memberof PricelistListPriceListsRequest
     */
    'filterMask'?: string;
    /**
     * 
     * @type {ListPriceListsRequestFilter}
     * @memberof PricelistListPriceListsRequest
     */
    'filter'?: ListPriceListsRequestFilter;
}
