/* tslint:disable */
/* eslint-disable */
/**
 * PriceList Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface PricelistSetPriceListItemPrice
 */
export interface PricelistSetPriceListItemPrice {
    /**
     * 
     * @type {PricelistMoney}
     * @memberof PricelistSetPriceListItemPrice
     */
    'price'?: PricelistMoney;
    /**
     * 
     * @type {boolean}
     * @memberof PricelistSetPriceListItemPrice
     */
    'isEnabled'?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof PricelistSetPriceListItemPrice
     */
    'startAt'?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PricelistSetPriceListItemPrice
     */
    'endAt'?: Date;
    /**
     * 
     * @type {number}
     * @memberof PricelistSetPriceListItemPrice
     */
    'order'?: number;
    /**
     * 
     * @type {PricelistMoney}
     * @memberof PricelistSetPriceListItemPrice
     */
    'basePrice'?: PricelistMoney;
}
