/* tslint:disable */
/* eslint-disable */
/**
 * PriceList Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface PricelistGetPriceItem
 */
export interface PricelistGetPriceItem {
    /**
     * 
     * @type {string}
     * @memberof PricelistGetPriceItem
     */
    'itemGrn'?: string;
    /**
     * 
     * @type {PricelistMoney}
     * @memberof PricelistGetPriceItem
     */
    'price'?: PricelistMoney;
    /**
     * 
     * @type {number}
     * @memberof PricelistGetPriceItem
     */
    'doubleFormatPrice'?: number;
    /**
     * 
     * @type {Date}
     * @memberof PricelistGetPriceItem
     */
    'endDatePrice'?: Date;
    /**
     * 
     * @type {PricelistMoney}
     * @memberof PricelistGetPriceItem
     */
    'basePrice'?: PricelistMoney;
    /**
     * 
     * @type {number}
     * @memberof PricelistGetPriceItem
     */
    'doubleFormatBasePrice'?: number;
    /**
     * 
     * @type {PricelistCurrency}
     * @memberof PricelistGetPriceItem
     */
    'currency'?: PricelistCurrency;
    /**
     * 
     * @type {boolean}
     * @memberof PricelistGetPriceItem
     */
    'hasTierPrices'?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof PricelistGetPriceItem
     */
    'createdAt'?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PricelistGetPriceItem
     */
    'updatedAt'?: Date;
}
