/* tslint:disable */
/* eslint-disable */
/**
 * PriceList Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface PricelistSetPriceListItem
 */
export interface PricelistSetPriceListItem {
    /**
     * 
     * @type {string}
     * @memberof PricelistSetPriceListItem
     */
    'itemGrn'?: string;
    /**
     * 
     * @type {PricelistMoney}
     * @memberof PricelistSetPriceListItem
     */
    'basePrice'?: PricelistMoney;
    /**
     * 
     * @type {Array<PricelistSetPriceListItemPrice>}
     * @memberof PricelistSetPriceListItem
     */
    'priceItems'?: Array<PricelistSetPriceListItemPrice>;
    /**
     * 
     * @type {boolean}
     * @memberof PricelistSetPriceListItem
     */
    'hasTierPrices'?: boolean;
}
