/* tslint:disable */
/* eslint-disable */
/**
 * PriceList Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PricelistPriceListType = {
    Unknown: 'UNKNOWN',
    Base: 'BASE',
    CatalogPromotion: 'CATALOG_PROMOTION'
} as const;
export type PricelistPriceListType = typeof PricelistPriceListType[keyof typeof PricelistPriceListType];


export function PricelistPriceListTypeFromJSON(json: any): PricelistPriceListType {
    return PricelistPriceListTypeFromJSONTyped(json, false);
}

export function PricelistPriceListTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PricelistPriceListType {
    return json as PricelistPriceListType;
}

export function PricelistPriceListTypeToJSON(value?: PricelistPriceListType | null): any {
    return value as any;
}

