/* tslint:disable */
/* eslint-disable */
/**
 * PriceList Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface PricelistGetFullPriceItem
 */
export interface PricelistGetFullPriceItem {
    /**
     * 
     * @type {string}
     * @memberof PricelistGetFullPriceItem
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof PricelistGetFullPriceItem
     */
    'grn'?: string;
    /**
     * 
     * @type {string}
     * @memberof PricelistGetFullPriceItem
     */
    'itemGrn'?: string;
    /**
     * 
     * @type {PricelistMoney}
     * @memberof PricelistGetFullPriceItem
     */
    'basePrice'?: PricelistMoney;
    /**
     * 
     * @type {Date}
     * @memberof PricelistGetFullPriceItem
     */
    'createdAt'?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PricelistGetFullPriceItem
     */
    'updatedAt'?: Date;
    /**
     * 
     * @type {PricelistCurrency}
     * @memberof PricelistGetFullPriceItem
     */
    'currency'?: PricelistCurrency;
    /**
     * 
     * @type {Array<PricelistGetFullPriceItemPrice>}
     * @memberof PricelistGetFullPriceItem
     */
    'prices'?: Array<PricelistGetFullPriceItemPrice>;
    /**
     * 
     * @type {boolean}
     * @memberof PricelistGetFullPriceItem
     */
    'hasTierPrices'?: boolean;
}
