/* tslint:disable */
/* eslint-disable */
/**
 * PriceList Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface PricelistGetPriceListResponse
 */
export interface PricelistGetPriceListResponse {
    /**
     * 
     * @type {string}
     * @memberof PricelistGetPriceListResponse
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof PricelistGetPriceListResponse
     */
    'grn'?: string;
    /**
     * 
     * @type {string}
     * @memberof PricelistGetPriceListResponse
     */
    'code'?: string;
    /**
     * 
     * @type {string}
     * @memberof PricelistGetPriceListResponse
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof PricelistGetPriceListResponse
     */
    'description'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PricelistGetPriceListResponse
     */
    'isActive'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PricelistGetPriceListResponse
     */
    'isDefault'?: boolean;
    /**
     * 
     * @type {PricelistCurrency}
     * @memberof PricelistGetPriceListResponse
     */
    'currency'?: PricelistCurrency;
    /**
     * 
     * @type {boolean}
     * @memberof PricelistGetPriceListResponse
     */
    'vatIncluded'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PricelistGetPriceListResponse
     */
    'deliveredDutyPaid'?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof PricelistGetPriceListResponse
     */
    'segments'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PricelistGetPriceListResponse
     */
    'markets'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PricelistGetPriceListResponse
     */
    'channels'?: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof PricelistGetPriceListResponse
     */
    'createdAt'?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PricelistGetPriceListResponse
     */
    'updatedAt'?: Date;
    /**
     * 
     * @type {PricelistPriceListType}
     * @memberof PricelistGetPriceListResponse
     */
    'type'?: PricelistPriceListType;
    /**
     * 
     * @type {boolean}
     * @memberof PricelistGetPriceListResponse
     */
    'isSystem'?: boolean;
}
