/* tslint:disable */
/* eslint-disable */
/**
 * PriceList Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PricelistFilterCondition = {
    In: 'IN',
    NotIn: 'NOT_IN'
} as const;
export type PricelistFilterCondition = typeof PricelistFilterCondition[keyof typeof PricelistFilterCondition];


export function PricelistFilterConditionFromJSON(json: any): PricelistFilterCondition {
    return PricelistFilterConditionFromJSONTyped(json, false);
}

export function PricelistFilterConditionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PricelistFilterCondition {
    return json as PricelistFilterCondition;
}

export function PricelistFilterConditionToJSON(value?: PricelistFilterCondition | null): any {
    return value as any;
}

