/**
 * pricelist/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ListPriceListsRequestFilter } from '../models/ListPriceListsRequestFilter';
import { HttpFile } from '../http/http';

export class PricelistListPriceListsRequest {
    'tenantId'?: string;
    'pageSize'?: number;
    'pageToken'?: string;
    'searchQuery'?: string;
    'filterMask'?: string;
    'filter'?: ListPriceListsRequestFilter;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tenantId",
            "baseName": "tenantId",
            "type": "string",
            "format": ""
        },
        {
            "name": "pageSize",
            "baseName": "pageSize",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "pageToken",
            "baseName": "pageToken",
            "type": "string",
            "format": ""
        },
        {
            "name": "searchQuery",
            "baseName": "searchQuery",
            "type": "string",
            "format": ""
        },
        {
            "name": "filterMask",
            "baseName": "filterMask",
            "type": "string",
            "format": ""
        },
        {
            "name": "filter",
            "baseName": "filter",
            "type": "ListPriceListsRequestFilter",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PricelistListPriceListsRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

