/**
 * PriceList Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PricelistSetPriceListItemError } from '../models/PricelistSetPriceListItemError';
import { HttpFile } from '../http/http';

export class PricelistSetPriceListItemsResponse {
    'errors'?: PricelistSetPriceListItemError;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "errors",
            "baseName": "errors",
            "type": "PricelistSetPriceListItemError",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PricelistSetPriceListItemsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

