/**
 * PriceList Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PricelistFilterCondition } from '../models/PricelistFilterCondition';
import { PricelistPriceListType } from '../models/PricelistPriceListType';
import { HttpFile } from '../http/http';

export class PricelistPriceListTypeFilter {
    'pricelistTypes'?: Array<PricelistPriceListType>;
    'condition'?: PricelistFilterCondition;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "pricelistTypes",
            "baseName": "pricelistTypes",
            "type": "Array<PricelistPriceListType>",
            "format": ""
        },
        {
            "name": "condition",
            "baseName": "condition",
            "type": "PricelistFilterCondition",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PricelistPriceListTypeFilter.attributeTypeMap;
    }

    public constructor() {
    }
}



