/**
 * PriceList Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PricelistPriceContext } from '../models/PricelistPriceContext';
import { HttpFile } from '../http/http';

export class PricelistGetPricesRequest {
    'tenantId'?: string;
    'itemsGrn'?: Array<string>;
    'context'?: PricelistPriceContext;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tenantId",
            "baseName": "tenantId",
            "type": "string",
            "format": ""
        },
        {
            "name": "itemsGrn",
            "baseName": "itemsGrn",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "context",
            "baseName": "context",
            "type": "PricelistPriceContext",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PricelistGetPricesRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

