/**
 * pricelist/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PricelistMoney } from '../models/PricelistMoney';
import { PricelistSetPriceListItemPrice } from '../models/PricelistSetPriceListItemPrice';
import { HttpFile } from '../http/http';

export class PricelistSetPriceListItem {
    'itemGrn'?: string;
    'basePrice'?: PricelistMoney;
    'priceItems'?: Array<PricelistSetPriceListItemPrice>;
    'hasTierPrices'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "itemGrn",
            "baseName": "itemGrn",
            "type": "string",
            "format": ""
        },
        {
            "name": "basePrice",
            "baseName": "basePrice",
            "type": "PricelistMoney",
            "format": ""
        },
        {
            "name": "priceItems",
            "baseName": "priceItems",
            "type": "Array<PricelistSetPriceListItemPrice>",
            "format": ""
        },
        {
            "name": "hasTierPrices",
            "baseName": "hasTierPrices",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PricelistSetPriceListItem.attributeTypeMap;
    }

    public constructor() {
    }
}

