/**
 * PriceList Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PricelistMoney } from '../models/PricelistMoney';
import { HttpFile } from '../http/http';

export class PricelistSetPriceListItemPrice {
    'price'?: PricelistMoney;
    'isEnabled'?: boolean;
    'startAt'?: Date;
    'endAt'?: Date;
    'order'?: number;
    'basePrice'?: PricelistMoney;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "price",
            "baseName": "price",
            "type": "PricelistMoney",
            "format": ""
        },
        {
            "name": "isEnabled",
            "baseName": "isEnabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "startAt",
            "baseName": "startAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "endAt",
            "baseName": "endAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "order",
            "baseName": "order",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "basePrice",
            "baseName": "basePrice",
            "type": "PricelistMoney",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PricelistSetPriceListItemPrice.attributeTypeMap;
    }

    public constructor() {
    }
}

