/**
 * pricelist/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ListPriceListsResponsePriceList } from '../models/ListPriceListsResponsePriceList';
import { HttpFile } from '../http/http';

export class PricelistListPriceListsResponse {
    'pricelists'?: Array<ListPriceListsResponsePriceList>;
    'nextPageToken'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "pricelists",
            "baseName": "pricelists",
            "type": "Array<ListPriceListsResponsePriceList>",
            "format": ""
        },
        {
            "name": "nextPageToken",
            "baseName": "nextPageToken",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PricelistListPriceListsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

